version: '3'
services:
  datasette:
    image: datasetteproject/datasette:latest
    ports:
      - "8001:8001"
    volumes:
      - "./cf-database.db:/mnt/cf-database.db"
    command: "datasette -p 8001 -h 0.0.0.0 /mnt/cf-database.db"