name: cf-database
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pytest
  - pygraphviz
  - sqlalchemy
  - click
  - rich
  - typer
  - requests_cache
  - pip:
      - eralchemy2
      - ruamel.yaml
      - xonsh
      - conda_package_streaming
