name: Build conda environment & test
description: Builds conda environment for the docker images

inputs:
  env_file:
    description: Source path to environment file
    required: true
    type: string
  # Increase this value to reset cache manually
  cache-number:
    description: Number add to the cache key name
    required: false
    default: 0
    type: string

runs:
  using: composite

  steps:
    - name: Get environment name from file
      id: environment
      run: |
        echo "Getting environment name from file"
        echo ::set-output name=environment-name::$(grep name ${{ inputs.env_file }} | awk '{ print $2}' )
      shell: bash

    - name: Set cache date
      run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
      shell: bash

    # Cache action can't be modularized as a custom action, so we need to run it explicitly
    - uses: actions/cache@v3
      id: cache
      with:
        path: |
          - ~/conda_pkgs_dir
          - /usr/share/miniconda3/envs/${{ steps.environment.outputs.environment-name }}
        key: ${{ runner.os }}-conda-${{ steps.environment.outputs.environment-name }}-${{ env.DATE }}-${{ inputs.cache-number }}-${{ hashFiles( inputs.env_file ) }}

    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true
        activate-environment: ${{ steps.environment.outputs.environment-name }}
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

    - name: Update environment (hash changed)
      run: mamba env update --file ${{ inputs.env_file }} -n ${{ steps.environment.outputs.environment-name }}
      shell: bash -l {0}
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Skip environment update (hash unchanged)
      run: echo "Environment hash unchanged, skipping update"
      shell: bash -l {0}
      if: steps.cache.outputs.cache-hit == 'true'

    - name: Show environment dependencies
      run: conda list -n ${{ steps.environment.outputs.environment-name }}
      shell: bash -l {0}
