name: Create & Update DB

on: [pull_request, workflow_dispatch]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash -el {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build environment
      uses: ./.github/actions/build-conda-env
      with:
        env_file: environment.yaml

    - name: Activate environment & check conda info
      run: |
        conda activate $(grep name environment.yaml | awk '{ print $2}')
        conda info

    - name: Create runtest directory
      run: |
        mkdir database
        cd database

    - name: Retrieve previous DB table from artifacts
      uses: actions/download-artifact@v2
      with:
        name: my-db-table
        path: ./cf-database.db

    - name: Clone Feedstock Outputs
      if: always()
      run: |
        git clone https://github.com/conda-forge/feedstock-outputs.git
        echo "FEEDSTOCK_OUTPUTS=$(pwd)/feedstock-outputs" >> $GITHUB_ENV

    - name: Clone Artifacts (import_to_package_maps -- sparse)
      if: always()
      run: |
        mkdir libcfgraph && cd libcfgraph
        git init
        git config core.sparsecheckout true
        echo "import_to_pkg_maps" >> .git/info/sparse-checkout
        git remote add origin https://github.com/regro/libcfgraph.git
        git pull --depth=1 origin master
        echo "IMPORT_TO_PACKAGES=$(pwd)/libcfgraph/import_to_pkg_maps" >> $GITHUB_ENV


    - name: Populate table
      if: always()
      run: |
        cd ..
        echo $(pwd)
        echo "Update feedstock outputs"
        python -m cfdb update-feedstock-outputs -p $FEEDSTOCK_OUTPUTS
        echo "Update import Packages to maps"
        python -m cfdb update-import-to-package-maps --path $IMPORT_TO_PACKAGES

    - name: 'Upload Artifact'
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: my-db-table
        path: ./cf-database.db