name: Create & Update DB

on: [pull_request, workflow_dispatch]

env:
  CFDB_ARTIFACTS_PATH: ${{ github.workspace }}/harvested_artifacts
  CFDB_DB_PATH: ${{ github.workspace }}/cf-database.db

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash -el {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Clone Feedstock Outputs
      if: always()
      uses: actions/checkout@v3
      with:
        repository: conda-forge/feedstock-outputs
        path: feedstock-outputs

    - name: Clone Artifacts (import_to_package_maps -- sparse)
      if: always()
      uses: actions/checkout@v3
      with:
        repository: regro/libcfgraph
        path: libcfgraph
        sparse-checkout: import_to_pkg_maps
        fetch-depth: 1

    - name: Verify cloned repos
      run: |
        ls -lat
        ls -lat ${{ github.workspace }}/feedstock-outputs
        ls -lat ${{ github.workspace }}/libcfgraph


    - name: Build environment
      uses: ./.github/actions/build-conda-env
      with:
        env_file: environment.yaml

    - name: Activate environment & check conda info
      run: |
        conda activate $(grep name environment.yaml | awk '{ print $2}')
        conda info
        echo "Install cfdb"
        pip install -e .

    - name: Retrieve previous DB table from artifacts
      uses: actions/download-artifact@v3
      id: download
      with:
        name: cfdb
        path: ${{ github.workspace }}

    # Add an extra step to decompress the tar file back to the original location
    - name: Decompress DB file
      run: |
        tar -xf ${{ steps.download.outputs.download-path }} -C ${{ github.workspace }}
        echo "Move DB file to workspace" $(pwd)
        mv ${{ github.workspace }}/${{ github.workspace }}/cf-database.db $CFDB_DB_PATH
        echo "Decompressed DB file" $(du -sh ${{ github.workspace }}/cf-database.db)

    - name: Test cfdb
      if: always()
      run: |
          echo "Test cfdb installation :::::" $(pwd)
          cfdb --help
          ls -lat .

    - name: Populate table of feedstock outputs and import to package maps
      if: always()
      run: |
        cd ..
        echo $(pwd)
        echo "Update feedstock outputs"
        cfdb update-feedstock-outputs -p ${{ github.workspace }}/feedstock-outputs
        echo "Update import Packages to maps"
        cfdb update-import-to-package-maps --path ${{ github.workspace }}/libcfgraph/import_to_pkg_maps
        du -sh $CFDB_DB_PATH
        ls -lat

    - name: Harvest Artifacts
      if: always()
      run: |
        cd ..
        echo $(pwd)
        echo "Harvest Artifacts from upstream"
        cfdb harvest-packages-and-artifacts --path $CFDB_DB_PATH
        du -sh $CFDB_ARTIFACTS_PATH
        ls -lat


    - name: Populate artifact and files tables
      if: always()
      run: |
        cd ..
        echo $(pwd)
        echo "Populate artifact and files tables"
        cfdb update-artifacts --path $CFDB_ARTIFACTS_PATH
        du -sh $CFDB_DB_PATH


    # Add the compression step using tar and Zstd
    - name: Compress DB file
      if: always()
      run: |
        ZSTD_NBTHREADS=4 ZSTD_CLEVEL=19 tar --zstd -cf ${{ github.workspace }}/cf-database.db.tar.zstd $CFDB_DB_PATH
        echo "Compressed DB file" $(du -sh ${{ github.workspace }}/cf-database.db.tar.zstd)

    - name: 'Upload Artifact'
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cfdb
        path: ${{ github.workspace }}/cf-database.db.tar.zstd