name: Run PyTest

on: [pull_request]

concurrency:
  # Concurrency group that uses the workflow name and PR number if available
  # or commit SHA as a fallback. If a new build is triggered under that
  # concurrency group while a previous build is running it will be canceled.
  # Repeated pushes to a PR will cancel all previous builds, while multiple
  # merges to main will not cancel.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash -el {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build environment
      uses: ./.github/actions/build-conda-env
      with:
        env_file: environment.yaml

    - name: Activate environment & check conda info
      run: |
        conda activate $(grep name environment.yaml | awk '{ print $2}')
        conda info

    - name: Run PyTest (Unit tests)
      run: python -m pytest tests/unitests
