name: Run PyTest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash -el {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build environment
      uses: ./.github/actions/build-conda-env
      with:
        env_file: environment.yaml

    - name: Run PyTest
      run: pytest cfdb/tests
