name: Run PyTest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true
        environment-file: environment.yaml
        activate-environment: cf-database

    - name: Activate Conda environment
      run: conda activate cf-database

    - name: Run PyTest
      run: pytest cfdb/tests
